refactor to inline can-i-deploy

diff --git a/.github/workflows/ci-build-publish.yml b/.github/workflows/ci-build-publish.yml
--- a/.github/workflows/ci-build-publish.yml
+++ b/.github/workflows/ci-build-publish.yml
@@ -28,6 +28,9 @@ on:
       pact_application_name:
         required: true
         type: string
+      pact_env:
+        required: true
+        type: string
 
 jobs:
   Artefact-Version:
@@ -80,14 +83,39 @@ jobs:
           echo "Building with ARTEFACT_VERSION=$ARTEFACT_VERSION"
           gradle build -DARTEFACT_VERSION=$ARTEFACT_VERSION
 
+#      - uses: hmcts/pact-can-i-deploy@main
+#        with:
+#          pact_broker_token: ${{ secrets.PACT_BROKER_TOKEN }}
+#          artefact_version: ${{ needs.Artefact-Version.outputs.artefact_version }}
+#          pact_application_name: ${{ inputs.pact_application_name }}
+
+  Provider-Deploy:
+    needs: [ Build ]
+    runs-on: ubuntu-latest
+    env:
+      ARTEFACT_VERSION: ${{ needs.Artefact-Version.outputs.artefact_version }}
+      PACT_BROKER_URL: "https://hmcts-dts.pactflow.io"
+      PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
+      PACT_ENV: ${{ inputs.pact_env }}
+      PACT_APPLICATION_NAME: ${{ inputs.pact_application_name }}
+    steps:
+      - name: Checkout source code
+        uses: actions/checkout@v4
+
+      - name: Set up JDK
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'temurin'
+          java-version: '21'
+
+      - name: Set up Gradle
+        uses: gradle/actions/setup-gradle@v4
+        with:
+          gradle-version: current
+
       - name: Pact Provider Verification and Publish Results
         env:
-          ARTEFACT_VERSION: ${{ needs.Artefact-Version.outputs.artefact_version }}
           GIT_BRANCH: ${{ github.ref_name }}
-          PACT_BROKER_URL: ${{ env.PACT_BROKER_BASE_URL }}
-          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
-          PACT_ENV: ${{ env.PACT_ENV }}
-          PACT_APPLICATION_NAME: ${{ inputs.pact_application_name }}
         run: |
           gradle pactVerificationTest \
             -Dpact.provider.version="$ARTEFACT_VERSION" \
@@ -97,11 +125,37 @@ jobs:
             -Dpact.broker.url="$PACT_BROKER_URL" \
             -Dpact.env="$PACT_ENV"
 
-      - uses: hmcts/pact-can-i-deploy@main
-        with:
-          pact_broker_token: ${{ secrets.PACT_BROKER_TOKEN }}
-          artefact_version: ${{ needs.Artefact-Version.outputs.artefact_version }}
-          pact_application_name: ${{ inputs.pact_application_name }}
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+
+      - name: Install Pact CLI
+        run: npm install -g @pact-foundation/pact-cli
+
+      - name: Tag Version
+        run: |
+          pact-broker create-version-tag \
+            --pacticipant "$PACT_APPLICATION_NAME" \
+            --version "$ARTEFACT_VERSION" \
+            --tag "$PACT_ENV" \
+            --broker-base-url "$PACT_BROKER_URL" \
+            --broker-token "$PACT_BROKER_TOKEN"
+
+      - name: Can I Deploy
+        run: |
+          pact-broker can-i-deploy \
+            --pacticipant "$PACT_APPLICATION_NAME" \
+            --version "$ARTEFACT_VERSION" \
+            --to-environment "$PACT_ENV" \
+            --broker-base-url "$PACT_BROKER_URL" \
+            --broker-token "$PACT_BROKER_TOKEN" \
+            --output table
+          can_i_deploy_status=$?
+          if [ "$can_i_deploy_status" -ne 0 ]; then
+            echo "❌ Can-I-Deploy failed — this version is NOT safe to deploy to $PACT_ENV - (deploy status: $can_i_deploy_status)"
+            exit 1
+          else
+            echo "✅ Can-I-Deploy succeeded — this version is safe to deploy to $PACT_ENV"
+          fi
 
       - name: Gradle Publish
         if: ${{ inputs.is_publish }}
