revert to installing az cli

diff --git a/.github/workflows/ci-draft.yml b/.github/workflows/ci-draft.yml
--- a/.github/workflows/ci-draft.yml
+++ b/.github/workflows/ci-draft.yml
@@ -138,7 +138,6 @@ jobs:
             BASE_IMAGE=openjdk:21-jdk-slim
             JAR_FILENAME=${{ needs.Build.outputs.artefact_name }}.jar
 
-  # https://github.com/marketplace/actions/azure-pipelines-action
   Deploy:
     needs: [ Build, Artefact-Version ]
     runs-on: ubuntu-latest
@@ -151,6 +150,7 @@ jobs:
       ARTEFACT_GROUP_ID: uk.gov.hmcts.cp
 
     steps:
+      # https://github.com/marketplace/actions/azure-pipelines-action
       - name: Trigger ADO pipeline
         uses: Azure/pipelines@v1
         with:
@@ -164,51 +164,54 @@ jobs:
               "ARTIFACT_VERSION" : "${{ needs.Artefact-Version.outputs.draft_version}}"
             }
 
+      - name: Install Azure CLI
+        run: |
+          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+
       - name: Wait for ADO pipeline to complete
-        uses: azure/cli@v2
-        with:
-          inlineScript: |
-            echo "Fetching pipeline run ID..."
-            RUN_ID=$(az pipelines runs list \
-              --org https://dev.azure.com/${ADO_ORG} \
-              --project ${ADO_PROJECT} \
-              --query "[?definition.name=='${ADO_PIPELINE}'] | [0].id" -o tsv)
-  
-            echo "Monitoring pipeline run ID: $RUN_ID"
-            if [[ -z "$RUN_ID" ]]; then
-              echo "❌ Failed to retrieve pipeline run ID. Exiting."
-              exit 1
-            fi
-  
-            STATUS=""
-            TIMEOUT=10  # Max 5 minutes (10 * 30s)
-            COUNT=0
-            while [[ "$STATUS" != "completed" && "$STATUS" != "canceled" && "$STATUS" != "failed" && $COUNT -lt $TIMEOUT ]]; do
-              STATUS=$(az pipelines runs show \
-                --id $RUN_ID \
-                --org https://dev.azure.com/${ADO_ORG} \
-                --project ${ADO_PROJECT} \
-                --query 'status' -o tsv)
-              echo "Current status: $STATUS"
-              ((COUNT++))
-              sleep 30
-            done
-            if [[ $COUNT -ge $TIMEOUT ]]; then
-              echo "⚠️ Timed out waiting for Azure DevOps pipeline to complete. Please check the pipeline manually for status."
-              exit 0
-            fi
-  
-            RESULT=$(az pipelines runs show \
+        env:
+          AZURE_DEVOPS_EXT_PAT: ${{ secrets.HMCTS_ADO_PAT }}
+        run: |
+           curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+           echo "Fetching pipeline run ID..."
+           RUN_ID=$(az pipelines runs list \
+             --org https://dev.azure.com/${ADO_ORG} \
+             --project ${ADO_PROJECT} \
+             --query "[?definition.name=='${ADO_PIPELINE}'] | [0].id" -o tsv)
+           
+           echo "Monitoring pipeline run ID: $RUN_ID"
+           if [[ -z "$RUN_ID" ]]; then
+             echo "❌ Failed to retrieve pipeline run ID. Exiting."
+             exit 1
+           fi
+           
+           STATUS=""
+           TIMEOUT=10  # Max 5 minutes (10 * 30s)
+           COUNT=0
+           while [[ "$STATUS" != "completed" && "$STATUS" != "canceled" && "$STATUS" != "failed" && $COUNT -lt $TIMEOUT ]]; do
+             STATUS=$(az pipelines runs show \
               --id $RUN_ID \
               --org https://dev.azure.com/${ADO_ORG} \
               --project ${ADO_PROJECT} \
-              --query 'result' -o tsv)
-  
-            echo "Pipeline result: $RESULT"
-            if [[ "$RESULT" != "succeeded" ]]; then
-              echo "❌ Azure DevOps pipeline failed."
-  #            exit 1 TEMP SOFT EXIT UNTIL FIX ADO PIPELINE
-              exit 0
-            fi
-        env:
-          AZURE_DEVOPS_EXT_PAT: ${{ secrets.HMCTS_ADO_PAT }}
+              --query 'status' -o tsv)
+             echo "Current status: $STATUS"
+            ((COUNT++))
+             sleep 30
+           done
+           if [[ $COUNT -ge $TIMEOUT ]]; then
+             echo "⚠️ Timed out waiting for Azure DevOps pipeline to complete. Please check the pipeline manually for status."
+             exit 0
+           fi
+           
+           RESULT=$(az pipelines runs show \
+             --id $RUN_ID \
+             --org https://dev.azure.com/${ADO_ORG} \
+             --project ${ADO_PROJECT} \
+             --query 'result' -o tsv)
+           
+           echo "Pipeline result: $RESULT"
+             if [[ "$RESULT" != "succeeded" ]]; then
+             echo "❌ Azure DevOps pipeline failed."
+        #            exit 1 TEMP SOFT EXIT UNTIL FIX ADO PIPELINE
+             exit 0
+           fi
